image:
  name: hashicorp/terraform:light

stages:
  - validate
  - unit_test
  - plan
  - apply

validate:
  stage: validate
  script:
    - echo "Validate the terraform files"

unit_test:
  stage: unit_test
  script:
    - echo "Run Unit tests for terraform files"

plan:
  stage: plan
  script:
    - echo "Run plan stage of terraform"

apply:
  stage: apply
  script:
    - echo "Apply the terraform changes to production"
  dependencies:
    - plan