apiVersion: v2
name: monitoring
description: Monitoring solution using Grafana, Prometheus

type: application

version: 0.1.0

appVersion: 1.0.0

dependencies:
  - name: grafana
    version: "5.0.12"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  - name: prometheus
    version: "11.1.0"
    repository: "prometheus"
