apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <<DUMMY ARN>>
      username: <<DUMMY USERNAME>>
      groups:
        - system:bootstrappers
        - system:nodes
