replicaCount: 1

image:
  repository: <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/cats-web
  pullPolicy: IfNotPresent
  version: test

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

apiHost: "http://cats-api"
cdnHostname: "http://test/"

serviceAccount:
  create: true
  annotations: {}
  name: cats-web-service

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: cats-web.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
