replicaCount: 1

image:
  repository: <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/cats-api
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
dbUrl: postgres://username:password@machine/database

serviceAccount:
  create: true
  annotations: {}
  name: cats-api-service

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: cats-api.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
